version: "2"

services:
  node1:
    image: "progrium/consul"
    hostname: "node1"
    container_name: "node1"
    # volumes:
    #   - data:/data
    command: "-server -bootstrap-expect 3"

  node2:
    image: "progrium/consul"
    hostname: "node2"
    container_name: "node2"
    # volumes:
    #   - data:/data
    command: "-server -join ${JOIN_IP}"

  node3:
    image: "progrium/consul"
    hostname: "node3"
    container_name: "node3"
    # volumes:
    #   - data:/data
    command: "-server -join ${JOIN_IP}"

  node4:
    image: "progrium/consul"
    hostname: "node4"
    container_name: "node4"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    # volumes:
    #   - data:/data
    command: "-join ${JOIN_IP} -ui-dir /ui"

# volumes:
#   data:
#     external: true
