version: "2"

services:
  server1:
    image: "gliderlabs/consul-server"
    hostname: "server1"
    container_name: "server1"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: "-server -advertise 10.0.9.11 -bootstrap"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.11
    environment:
      - "constraint:node==master0"
    volumes:
      - data:/data

  server2:
    image: "gliderlabs/consul-server"
    hostname: "server2"
    container_name: "server2"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: "-server -advertise 10.0.9.12 -join ${JOIN_IP}"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.12
    environment:
      - "constraint:node==node0"
    volumes:
      - data:/data

  server3:
    image: "gliderlabs/consul-server"
    hostname: "server3"
    container_name: "server3"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: "-server -advertise 10.0.9.13 -join ${JOIN_IP}"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.13
    environment:
      - "constraint:node==node1"
    volumes:
      - data:/data

  agent1:
    image: "gliderlabs/consul-agent"
    hostname: "agent1"
    container_name: "agent1"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: " -advertise 10.0.9.14 -join ${JOIN_IP} -ui-dir /ui"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.14
    environment:
      - "constraint:node==node2"
    volumes:
      - data:/data

networks:
  demo_overlay_net:
    external: true

volumes:
  data:
    # external: true
