version: "3.0"

services:
  # consul:
  #   image: "consul:latest"
  #   hostname: "consul"
  #   # container_name: "consul"
  #   # network_mode: "host"
  #   command: "consul agent -server -ui -bootstrap-expect 3 -retry-join 10.0.9.2 -retry-join 10.0.9.3 -retry-join 10.0.9.4 -retry-interval 5s -data-dir=/consul/data"
  #   ports:
  #     - "8500:8500"
  #   networks:
  #     - consul_overlay_net
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints: [node.hostname != worker3]
  #   environment:
  #     # - "constraint:node.hostname != worker3"
  #     - "CONSUL_BIND_INTERFACE=eth0"
  #     - "SERVICE_IGNORE=true"
  #     - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
  #   volumes:
  #     - data:/consul/data
  #
  consul-server1:
    image: "consul:latest"
    hostname: "consul-server1"
    # network_mode: "host"
    command: "consul agent -server -ui -bootstrap-expect=3 -data-dir=/consul/data"
    networks:
      - consul_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == manager1]
    environment:
      - "CONSUL_CLIENT_INTERFACE=eth0"
      - "CONSUL_BIND_INTERFACE=eth1"
      - "SERVICE_IGNORE=true"
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    volumes:
      - data:/consul/data

  consul-server2:
    image: "consul:latest"
    hostname: "consul-server2"
    # network_mode: "host"
    command: "consul agent -server -retry-join=192.168.99.104 -data-dir=/consul/data"
    networks:
      - consul_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker1]
    environment:
      - "CONSUL_CLIENT_INTERFACE=eth0"
      - "CONSUL_BIND_INTERFACE=eth1"
      - "SERVICE_IGNORE=true"
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    volumes:
      - data:/consul/data

  consul-server3:
    image: "consul:latest"
    hostname: "consul-server3"
    # network_mode: "host"
    command: "consul agent -server -retry-join=192.168.99.104 -data-dir=/consul/data"
    networks:
      - consul_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker2]
    environment:
      - "CONSUL_CLIENT_INTERFACE=eth0"
      - "CONSUL_BIND_INTERFACE=eth1"
      - "SERVICE_IGNORE=true"
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    volumes:
      - data:/consul/data

  consul-agent1:
    image: "consul:latest"
    hostname: "consul-agent1"
    # network_mode: "host"
    command: "consul agent -retry-join=192.168.99.104 -data-dir=/consul/data"
    networks:
      - consul_overlay_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker3]
    environment:
      - "CONSUL_CLIENT_INTERFACE=eth0"
      - "CONSUL_BIND_INTERFACE=eth1"
      - "SERVICE_IGNORE=true"
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true}"
    volumes:
      - data:/consul/data
  #
  # registrator:
  #   image: "gliderlabs/registrator:latest"
  #   hostname: "registrator"
  #   networks:
  #     - consul_overlay_net
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints: [node.hostname != manager1]
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #   command: "-internal consul://192.168.99.104:8500"

networks:
  consul_overlay_net:
    # driver: overlay
    external: true
    # ipam:
    #   driver: default
    #   config:
    #   - subnet: 10.0.9.0/24
    #     gateway: 10.0.9.1

volumes:
  data:
    external: true
