version: "2"

services:
  server1:
    image: "gliderlabs/consul-server:latest"
    hostname: "server1"
    container_name: "server1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "-server -bootstrap -ui-dir /ui"
