version: "2"

services:
  server1:
    image: "gliderlabs/consul-server"
    hostname: "server1"
    container_name: "server1"
    command: "-server -bootstrap-expect 3"

  server2:
    image: "gliderlabs/consul-server"
    hostname: "server2"
    container_name: "server2"
    command: "-server -join ${JOIN_IP}"

  server3:
    image: "gliderlabs/consul-server"
    hostname: "server3"
    container_name: "server3"
    command: "-server -join ${JOIN_IP}"

  agent1:
    image: "gliderlabs/consul-agent"
    hostname: "agent1"
    container_name: "agent1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "-join ${JOIN_IP} -ui-dir /ui"
