version: "2"

services:
  server1:
    image: "gliderlabs/consul-server:latest"
    hostname: "server1"
    container_name: "server1"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: "-server -advertise 10.0.9.11 -bootstrap"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.11
    environment:
      - "constraint:node.hostname == master0"
      - "SERVICE_IGNORE=true"
    volumes:
      - data:/data

  server2:
    image: "gliderlabs/consul-server:latest"
    hostname: "server2"
    container_name: "server2"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: "-server -advertise 10.0.9.12 -join ${JOIN_IP}"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.12
    environment:
      - "constraint:node.hostname == node0"
      - "SERVICE_IGNORE=true"
    volumes:
      - data:/data

  server3:
    image: "gliderlabs/consul-server:latest"
    hostname: "server3"
    container_name: "server3"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: "-server -advertise 10.0.9.13 -join ${JOIN_IP}"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.13
    environment:
      - "constraint:node.hostname == node1"
      - "SERVICE_IGNORE=true"
    volumes:
      - data:/data

  agent1:
    image: "gliderlabs/consul-agent:latest"
    hostname: "agent1"
    container_name: "agent1"
    ports:
        - "53:53"
        - "8300:8300"
        - "8301:8301"
        - "8302:8302"
        - "8400:8400"
        - "8500:8500"
        - "53/udp:53/udp"
        - "8301/udp:8301/udp"
        - "8302/udp:8302/udp"
    command: "-advertise 10.0.9.14 -join ${JOIN_IP} -ui-dir /ui"
    networks:
      demo_overlay_net:
        ipv4_address: 10.0.9.14
    environment:
      - "constraint:node.hostname == node2"
      - "SERVICE_IGNORE=true"
    volumes:
      - data:/data

  registrator:
    image: "gliderlabs/registrator:latest"
    hostname: "registrator"
    network_mode: "host"
    environment:
      - "constraint:node.hostname != master0"
      - "SERVICE_IGNORE=true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "consul://localhost:8500"

networks:
  demo_overlay_net:
    external: true

volumes:
  data:
    external: true
