version: '3.0'

services:
  # registrator:
  #   image: gliderlabs/registrator:latest
  #   command: ['-internal', "consul://${CONSUL_SERVER}:8500"]
  #   hostname: registrator
  #   networks:
  #   - widget_overlay_net
  #   volumes:
  #   - /var/run/docker.sock:/tmp/docker.sock
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints:
  #       - node.role == worker
  #   environment:
  #     SERVICE_IGNORE: 'true'
  #     SERVICE_NAME: registrator
  #     SERVICE_TAGS: monitoring

  visualizer:
    image: manomarks/visualizer:latest
    hostname: visualizer
    ports:
    - 5001:8080
    networks:
    - widget_overlay_net
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == manager
    environment:
      # SERVICE_IGNORE: 'true'
      SERVICE_NAME: visualizer
      SERVICE_TAGS: monitoring

  elk:
    image: sebp/elk:latest
    hostname: elk
    ports:
    - "5601:5601/tcp"
    - "9200:9200/tcp"
    - "5044:5044/tcp"
    depends_on:
    - fluentd
    networks:
    - widget_overlay_net
    volumes:
    - widget_data_vol:/var/lib/elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == worker3]
    environment:
      # SERVICE_IGNORE: 'true'
      SERVICE_NAME: elk
      SERVICE_TAGS: monitoring

  fluentd:
    image: garystafford/custom-fluentd:latest
    hostname: fluentd
    ports:
    - "24224:24224/tcp"
    - "24224:24224/udp"
    networks:
    - widget_overlay_net
    # volumes:
    # - /Users/gstaffo/Documents/projects/widget-docker-demo/widget-service/scripts/fluent.conf:/fluentd/etc/fluent.conf
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == worker
        - node.hostname != worker3
    environment:
      # SERVICE_IGNORE: 'true'
      SERVICE_NAME: fluentd
      SERVICE_TAGS: monitoring

networks:
  widget_overlay_net:
    external: true

volumes:
  widget_data_vol:
    external: true
